version: '3'

services:
  node-app:
    build:
      context: .
      target: build
    ports:
      - "8000:8000"
      - "3001:3001"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
